const games = [
  "The Lord of the Rings / J.R.R. Tolkien",
  "Pride and Prejudice / Jane Austin",
  "His Dark Materials / Philip Pullman",
  "The Hitchhiker's Guide to the Galaxy / Douglas Adams",
  "Harry Potter and the Goblet of Fire / J.K. Rowling",
  "Ulysses / James Joyce",
  "The Great Gatsby / F. Scott Fitzgerald",
  "Moby Dick / Herman Melville",
  "War and Peace / Leo Tolstoy",
  "The Odyssey / Homer",
  "Great Expectations / Charles Dickens",
  "The Old Man and the Sea / Ernest Hemingway",
  "The Iliad / Homer",
  "King Lear / William Shakespeare",
  "Othello / William Shakespeare",
  "Gulliver's Travels / Jonathon Swift",
  "The Canterbury Tales / Geoffrey Chaucer",
  "The Raven / Edgar Allan Poe",
  "Middlemarch / George Eliot",
  "Midnight's Children / Salman Rushdie",
  "The Invisible Man / H.G. Wells",
  "Wuthering Heights / Emily Bronte",
  "The Adventures of Huckleberry Finn / Mark Twain",
  "To Kill a Mockingbird / Harper Lee",
  "Jane Eyre / Charlotte Bronte",
  "Les Miserables / Victor Hugo",
  "Frankenstein / Mary Shelley",
  "Nineteen Eighty-Four / George Orwell",
  "The Catcher in the Rye / J.D. Salinger",
  "Dracula / Bram Stoker",
  "Tess of the D'Urbervilles / Thomas Hardy",
  "Brideshead Revisited / Evelyn Waugh",
  "Alice's Adventures in Wonderland / Lewis Carroll",
  "Charlie and the Chocolate Factory / Roald Dahl",
  "The Count of Monte Cristo / Alexander Dumas",
  "The Three Musketeers / Alexander Dumas",
  "The Grapes of Wrath / John Steinbeck",
  "The Lion, The Witch and The Wardrobe / C.S. Lewis",
  "A Tale of Two Cities / Charles Dickens",
  "The Time Machine / H.G. Wells",
  "A Christmas Carol / Charles Dickens",
  "Little Women / Louisa May Alcott",
  "Peter Pan / J.M. Barrie",
  "The Handmaid's Tale / Margaret Atwood",
  "The War of the Worlds / H.G. Wells",
  "How to Train Your Dragon / Cressida Cowell",
  "The Adventures of Sherlock Holmes / Arthur Conan Doyle",
  "The Hound of the Baskervilles / Arthur Conan Doyle"
]

const books = () => games.map(game => ({
  game,
  hint: 'book & author'
}))

export default books
