const games = [
  "FIFA World Cup",
  "The Olympic Games",
  "The Super Bowl",
  "Wimbledon Tennis Championships",
  "Tour de France",
  "Rugby World Cup",
  "The Grand Prix",
  "The Masters Golf Tournament",
  "New York City Marathon",
  "Baseball World Series",
  "The Winter Olympics",
  "The Ryder Cup",
  "The Kentucky Derby",
  "Monaco Grand Prix",
  "The French Open Tennis Tournament",
  "The FA Cup",
  "U.S. Open Golf Championship",
  "The Boston Marathon",
  "The Australian Open Tennis Tournament",
  "The London Marathon",
  "The Paralympic Games",
  "The Invictus Games",
  "The Grand National",
  "The Commonwealth Games",
  "Burn's Night",
  "The Six Nations Rugby Championships",
  "Chinese New Year",
  "Glasgow Film Festival",
  "St. David's Day",
  "St. Patrick's Day",
  "St. George's Day",
  "St. Andrew's Day",
  "The Oxford & Cambridge Boat Race",
  "The Highland Games",
  "The Chelsea Flower Show",
  "Urdd Eisteddfod",
  "Trooping of the Color",
  "Changing of the Guard",
  "The Summer Solstice",
  "The Winter Solstice",
  "The Spring Equinox",
  "The Autumn Equinox",
  "The Last Night of The Proms",
  "The Royal Welsh Show",
  "The World Bog Snorkelling Championships",
  "The Notting Hill Carnival",
  "Blackpool Illuminations",
  "The Great North Run",
  "Bonfire Night",
  "St. Valentine's Day",
  "Dydd Santes Dwynwen",
  "New Year's Day",
  "Pancake Day",
  "Shrove Tuesday",
  "Mothering Sunday",
  "Father's Day",
  "Easter Sunday",
  "April Fool's Day",
  "Harvest Festival",
  "Halloween",
  "Remembrance Day",
  "Christmas Day",
  "Boxing Day",
  "Wedding Anniversary",
  "Birthday Party",
  "Stag Night",
  "Hen Night",
  "American Day of Independence",
  "American Thanks Giving",
]

const event = () => games.map(game => ({
  game,
  hint: 'event'
}))

export default event
