const games = [
  "The Shawshank Redemption",
  "The Godfather",
  "The Dark Knight",
  "Schindler's List",
  "The Lord of the Rings: The Return of the King",
  "Pulp Fiction",
  "The Lord of the Rings: The Fellowship of the Ring",
  "The Good, the Bad and the Ugly",
  "Forrest Gump",
  "The Lord of the Rings: The Two Towers",
  "Fight Club",
  "Star Wars: Episode V - The Empire Strikes Back",
  "The Matrix",
  "Goodfellas",
  "One Flew Over the Cuckoo's Nest",
  "Interstellar",
  "It's a Wonderful Life",
  "The Silence of the Lambs",
  "Saving Private Ryan",
  "The Green Mile",
  "Star Wars: Episode IV - A New Hope",
  "Back to the Future",
  "Psycho",
  "Gladiator",
  "The Usual Suspects",
  "Casablanca",
  "Rear Window",
  "Alien",
  "Apocalypse Now",
  "Raiders of the Lost Ark",
  "Avengers: Infinity War",
  "The Shining",
  "The Dark Knight Rises",
  "American Beauty",
  "Toy Story",
  "Avengers: Endgame",
  "Braveheart",
  "Good Will Hunting",
  "Princess Mononoke",
  "Joker",
  "Singin' in the Rain",
  "Star Wars: Episode VI - Return of the Jedi",
  "Oppenheimer",
  "Reservoir Dogs",
  "Lawrence of Arabia",
  "Citizen Kane",
  "Vertigo",
  "Scarface",
  "Full Metal Jacket",
  "A Clockwork Orange",
  "Indiana Jones and the Last Crusade",
  "Die Hard",
  "For a Few Dollars More",
  "Batman Begins",
  "The Wolf of Wall Street",
  "The Truman Show",
  "Top Gun: Maverick",
  "Jurassic Park",
  "The Sixth Sense",
  "A Beautiful Mind",
  "Monty Python and the Holy Grail",
  "The Great Escape",
  "Finding Nemo",
  "Gone with the Wind",
  "Lock, Stock and Two Smoking Barrels",
  "Trainspotting",
  "Catch Me If You Can",
  "Harry Potter and the Deathly Hallows: Part II",
  "Blade Runner",
  "Ben-Hur",
  "Dead Poets Society",
  "Monsters Inc.",
  "How to Train Your Dragon",
  "The Terminator",
  "Pirates of the Caribbean: The Curse of the Black Pearl",
  "The Exorcist",
  "The Wizard of Oz",
  "Groundhog Day"
]

const film = () => games.map(game => ({
  game,
  hint: 'film'
}))

export default film
