const games = [
  "Fish and Chips",
  "Sausage and Chips",
  "Chicken Tikka Masala",
  "Salt and Vinegar Crisps",
  "Ready Salted Crisps",
  "Cheese and Onion Crisps",
  "Rhubarb Crumble",
  "Apple Pie",
  "Cherry Pie",
  "Vanilla Cheesecake",
  "Sausage and Mash Potato",
  "Cheese Burger and Chips",
  "Black Forest Gateaux",
  "Steak and Ale Pie",
  "Chicken and Mushroom Pie",
  "Tomato Soup",
  "Chicken Soup",
  "Lentil Soup",
  "Vegetable Soup",
  "Oxtail Soup",
  "Cornflakes",
  "Belgian Waffles",
  "Pancakes with Maple Syrup",
  "Chocolate Fudge Cake",
  "Chocolate Brownie",
  "Doner Kebab",
  "Chicken Jalfrezi",
  "Chicken Rogan Josh",
  "Cheese on Toast",
  "Welsh Rarebit",
  "Spaghetti Bolognese",
  "Macaroni Cheese",
  "Cauliflower Cheese",
  "Yorkshire Pudding",
  "Baked Beans on Toast",
  "Scrambled Egg on Toast",
  "Jaffa Cakes",
  "Jam Tarts",
  "Jumbo Sausage Roll",
  "Jam Donut",
   "Chocolate Chip Cookies",
   "Cornish Pasty",
   "Full English Breakfast",
   "Croque Monsieur",
   "Croque Madame",
   "Cottage Pie",
   "Beef Hot Pot",
   "Margherita Pizza",
   "Pepperoni Pizza",
   "Shepherd's Pie",
   "Fisherman's Pie",
   "English Breakfast Tea",
   "Americano Coffee",
   "Pinot Grigio Wine",
   "Sauvignon Blanc Wine"
]

const food = () => games.map(game => ({
  game,
  hint: 'food & drink'
}))

export default food
