const games = [
  "Starship / Nothing's Gonna Stop Us Now",
  "Whitney Houston / I Wanna Dance With Somebody (Who Loves Me)",
  "Rick Astley / Never Gonna Give You Up",
  "Belinda Carlisle / Heaven Is A Place On Earth",
  "Tiffany / I Think We're Alone Now",
  "Kylie Minogue / I Should Be So Lucky",
  "Madonna / Like A Virgin",
  "The Bangles / Walk Like An Egyptian",
  "Billy Ocean / Get Outta My Dreams, Get Into My Car",
  "Billy Ocean / When The Going Gets Tough, The Tough Get Going",
  "Diana Ross / Chain Reaction",
  "Europe / The Final Countdown",
  "Dead Or Alive / You Spin Me Around (Like A Record)",
  "Band Aid / Do They Know it's Christmas?",
  "Frankie Goes To Hollywood / Relax",
  "Bonnie Tyler / Total Eclipse Of The Heart",
  "Spandau Ballet - Gold",
  "Culture Club / Karma Chameleon",
  "Billy Joel / Uptown Girl",
  "Madness / House Of Fun",
  "Madness / Our House",
  "Dexys Midnight Runners / Come On Eileen",
  "John Lennon / Imagine",
  "Bucks Fizz / Making Your Mind Up",
  "Adam and The Ants / Stand and Deliver",
  "Adam and The Ants / Prince Charming",
  "Queen and David Bowie / Under Pressure",
  "The Human League / Don't You Want Me",
  "Blondie / Atomic",
  "ABBA / The Winner Takes It All",
  "Maria McKee / Show Me Heaven",
  "The Clash / Should I Stay Or Should I Go",
  "Chesney Hawkes / The One And Only",
  "Cher / The Shoop Shoop Song (It's In His Kiss)",
  "Bryan Adams / (Everything I Do) I Do It For You",
  "Michael Jackson / Black Or White",
  "Queen / Bohemian Rhapsody",
  "The Shamen / Ebeneezer Goode",
  "Meat Loaf / I'd Do Anything For Love (But I Won't Do That)",
  "Wet Wet Wet / Love Is All Around",
  "Rednex / Cotten Eye Joe",
  "Blur / Country House",
  "Oasis / Don't Look Back In Anger",
  "The Prodigy / Firestarter",
  "Gina G / Ooh Aah... Just A Little Bit",
  "Spice Girls / Wannabe",
  "Deep Blue Something / Breakfast At Tiffany's",
  "The Verve / The Drugs Don't Work",
  "Elton John / Candle In The Wind",
  "Spice Girls / Spice Up Your Life",
  "Aqua / Barbie Girl",
  "Celine Dion / My Heart Will Go On",
  "Manic Street Preachers / If You Tolerate This Your Children Will Be Next",
  "Robbie Williams / Millennium",
  "Steps / Tragedy",
  "Ronan Keating / When You Say Nothing At All",
  "Westlife / Flying Without Wings",
  "Christina Aguilera / Genie In A Bottle",
  "Kylie Minogue / Spinning Around",
  "Eminem / The Real Slim Shady",
  "The Corrs / Breathless",
  "Bob The Builder / Can We Fix It?",
  "Destiny's Child / Survivor",
  "Kylie Minogue / Can't Get You Out Of My Head",
  "Elvis vs. JXL / A Little Less Conversation",
  "Pink / Just Like A Pill",
  "Girls Aloud / Sound Of The Underground",
  "James Blunt / You're Beautiful",
  "Kaiser Chiefs / I Predict A Riot",
  "Kaiser Chiefs / Ruby",
  "Shakira / Hips Don't Lie",
  "Take That / Patience",
  "Rhianna / Umbrella",
  "Lady Gaga / Poker Face",
  "Lady Gaga / Bad Romance",
  "Coldplay / Stars",
  "Coldplay / Fix You"
]

const music = () => games.map(game => ({
  game,
  hint: 'singer & song'
}))

export default music
