const games = [
  "A bad workman blames his tools",
  "A bird in the hand is worth two in the bush",
  "A chain is only as strong as its weakest link",
  "A dog is man's best friend",
  "A fool and his money are soon parted",
  "A friend in need is a friend indeed",
  "A leopard cannot change its spots",
  "A miss is as good as a mile",
  "A picture is worth a thousand words",
  "A rolling stone gathers no moss",
  "A stitch in time saves nine",
  "A watched pot never boils",
  "Absence makes the heart grow fonder",
  "Actions speak louder than words",
  "All good things must come to an end",
  "All roads lead to Rome",
  "All that glitters is not gold",
  "All work and no play makes Jack a dull boy",
  "All is fair in love and war",
  "All is well that ends well",
  "An apple a day keeps the doctor away",
  "An army marches on its stomach",
  "An eye for an eye, a tooth for a tooth",
  "An Englishman's home is his castle",
  "Another day, another dollar",
  "Any port in a storm",
  "Ask a silly question and you get a silly answer",
  "Ask no questions and hear no lies",
  "Attack is the best form of defence",
  "Bad news travels fast",
  "Beauty is in the eye of the beholder",
  "Beauty is only skin deep",
  "Beggars cannot be choosers",
  "Behind every great man, is a great woman",
  "Better late than never",
  "Better safe than sorry",
  "Better the Devil you know",
  "Better to have loved and lost than to have never loved at all",
  "Beware of Greeks bearing gifts",
  "Birds of a feather flock together",
  "Blood is thicker than water",
  "Business before pleasure",
  "Careless talk costs lives",
  "Charity begins at home",
  "Cheaters never prosper",
  "Children should be seen and not heard",
  "Cleanliness is next to godliness",
  "Cold hands, warm heart",
  "Count your blessings",
  "Crime does not pay",
  "Curiosity killed the cat",
  "Dead men tell no tales",
  "Discretion is the better part of valour",
  "Do as I say, not as I do",
  "Do unto others as you would have done unto you",
  "Do not bite the hand that feeds you",
  "Do not burn your bridges behind you",
  "Do not cast your pearls before swine",
  "Do not count your chickens before they hatch",
  "Do not cut off your nose to spite your face",
  "Do not let the grass grow beneath one's feet",
  "Do not make a mountain out of a mole hill",
  "Do not put all your eggs in one basket",
  "Do not put off until tomorrow what you can do today",
  "Do not rock the boat",
  "Do not teach your grandmother to suck eggs",
  "Do not throw the baby out with the bath water",
  "Do not upset the apple cart",
  "Do not wash your dirty linen in public",
  "Early to bed and early to rise makes a man healthy, wealthy and wise",
  "Easier said than done",
  "Easy come, easy go",
  "Every cloud has a silver lining",
  "Every dog has his day",
  "Every picture tells a story",
  "Failing to plan is planning to fail",
  "Familiarity breeds contempt",
  "Feed a cold, starve a fever",
  "Fight fire with fire",
  "Finders keepers (losers weepers)",
  "First come, first served",
  "Flattery will get you nowhere",
  "Fools rush in where angels fear to tread",
  "Forewarned is forearmed",
  "Fortune favours the brave",
  "From the sublime to the ridiculous (is only a step)",
  "Give a man enough rope and he will hang himself",
  "Give credit where credit is due",
  "God helps those who help themselves",
  "Good things come to those who wait",
  "Great minds think alike",
  "Hard work never did anyone harm",
  "He who hesitates is lost",
  "He who laughs last laughs longest",
  "He who lives by the sword, dies by the sword",
  "He who pays the piper calls the tune",
  "Hell hath no fury like a woman scorned",
  "Hindsight is always twenty-twenty",
  "History repeats itself",
  "Home is where the heart is",
  "Honesty is the best policy",
  "Hope for the best, and prepare for the worst",
  "If anything can go wrong, it will",
  "If a job is worth doing, it's worth doing well",
  "If at first you don't succeed, try, try again",
  "If it ain't broke, don't fix it",
  "If the shoe fits, were it",
  "If you cannot beat them, join them",
  "If you cannot stand the heat, get out of the kitchen",
  "If you pay peanuts, you get monkeys",
  "If you play with fire, you will get burned",
  "Imitation is the sincerest form of flattery",
  "In for a penny, in for a pound",
  "It ain't over till the fat lady sings",
  "It's better to give than to receive",
  "It's no use crying over spilt milk",
  "It never rains but it pours",
  "It takes one to know one",
  "It takes two to tango",
  "Jack of all trades, master of none",
  "Keep your friends close and enemies closer",
  "Laughter is the best medicine",
  "Let sleeping dogs lie",
  "Let the cat out of the bag",
  "Let the punishment fit the crime",
  "Life begins at forty",
  "Life is what you make it",
  "Like father, like son",
  "Little things please little minds",
  "Live and let live",
  "loose lips sink ships",
  "Look before you leap",
  "Make hay while the sun shines",
  "Man does not live by bread alone",
  "Many a true word is spoken in jest",
  "Many hands make light work",
  "Money does not grow on trees",
  "Money makes the world go around",
  "More haste, less speed",
  "Never let the truth get in the way of a good story",
  "Never look a gift horse in the mouth",
  "No man is an island",
  "No news is good news",
  "No pain, no gain",
  "No rest for the wicked",
  "Nothing is certain but death and taxes",
  "Nothing ventured, nothing gained",
  "Once bitten, twice shy",
  "One good turn deserves another",
  "One swallow does not make a summer",
  "Only fools and horses work",
  "Out of sight, out of mind",
  "Out of the frying pan and into the fire",
  "Patience is a virtue",
  "People who live in glass houses should not throw stones",
  "Power corrupts; absolute power corrupts absolutely",
  "Practice makes perfect",
  "Practice what you preach",
  "Preaching to the choir",
  "Prevention is better than cure",
  "Pride comes before a fall",
  "Putting the cart before the horse",
  "Put your best foot forward",
  "Put your money where your mouth is",
  "Red sky at night, shepherds delight",
  "Red sky in morning, shepherds warning",
  "Respect is not given, it is earned",
  "Revenge is a dish best served cold",
  "Rome was not built in a day",
  "Rules were made to be broken",
  "See no evil, hear no evil, speak no evil",
  "Still waters run deep",
  "The apple does not fall far from the tree",
  "The best defence is a good offence",
  "The best things in life are free",
  "The bigger they are, the harder they fall",
  "The customer is always right",
  "The darkest hour is just before the dawn",
  "The devil finds work for idle hands",
  "The early bird catches the worm",
  "The enemy of my enemy is my friend",
  "The female of the species is more deadlier than the male",
  "The light is on but nobody is home",
  "The longest journey starts with a single step",
  "The more things change, the more they stay the same",
  "The pen is mightier than the sword",
  "The proof of the pudding is in the eating",
  "The road to hell is paved with good intentions",
  "The squeaky wheel gets the grease",
  "The way to a man's heart is through his stomach",
  "There is many a good tune played on an old fiddle",
  "There is more than one way to skin a cat",
  "There is no accounting for tastes",
  "There is no fool like an old fool",
  "There is no place like home",
  "There is no smoke without fire",
  "There is no such thing as a free lunch",
  "There is no such thing as bad publicity",
  "There is no time like the present",
  "There is one born every minute",
  "Time and tide wait for no man",
  "Too many cooks spoil the broth",
  "Two heads are better than one",
  "Two is company but three is a crowd",
  "Two wrongs do not make a right",
  "Uneasy lies the head that wears a crown",
  "United we stand, divided we fall",
  "Use it or lose it",
  "Up a creek without a paddle",
  "Waste not, want not",
  "What goes around, comes around",
  "What goes up must come down",
  "What you lose on the swings you gain on the roundabouts",
  "What is sauce for the goose is sauce for the gander",
  "When life gives you lemons, make lemonade",
  "When the cat is away, the mice will play",
  "When the going gets tough, the tough get going",
  "When you have seen one, you have seen them all",
  "Where there is a will there is a way",
  "Where there is life there is hope",
  "Why keep a dog and bark yourself",
  "Wonders will never cease",
  "You are never too old to learn",
  "You can have too much of a good thing",
  "You can lead a horse to water, but you cannot make it drink",
  "You cannot burn a candle at both ends",
  "You cannot get blood out of a stone",
  "You cannot have your cake and eat it too",
  "You cannot make a silk purse out of a sow's ear",
  "You cannot make an omelette without breaking eggs",
  "You cannot teach an old dog new tricks",
  "You pay your money and you take your choice",
  "You may as well be hanged for a sheep as for a lamb",
  "You scratch my back and I will scratch yours",
  "You've got to separate the wheat from the chaff",
  "You've made your bed and you must lie in it"
]

const phrase = () => games.map(game => ({
  game,
  hint: 'phrase'
}))

export default phrase
