const games = [
  "London - England",
  "Cardiff - Wales",
  "Edinburgh - Scotland",
  "Belfast - Northern Ireland",
  "Dublin - Republic of Ireland",
  "Cork - Republic of Ireland",
  "Porto - Portugal",
  "Albufeira - Portugal",
  "Algarve - Portugal",
  "Lisbon - Portugal",
  "Barcelona - Spain",
  "Madrid - Spain",
  "Malaga - Spain",
  "Valencia - Spain",
  "Alicante - Spain",
  "Tenerife - Spain",
  "Majorca - Spain",
  "Paris - France",
  "Nice - France",
  "Lyon - France",
  "Strasbourg - France",
  "Berlin - Germany",
  "Munich - Germany",
  "Hamburg - Germany",
  "Cologne - Germany",
  "Frankfurt - Germany",
  "Rome - Italy",
  "Milan - Italy",
  "Venice - Italy",
  "Naples - Italy",
  "Oslo - Norway",
  "Lillehammer - Norway",
  "Helsinki - Finland",
  "Stockholm - Sweden",
  "Copenhagen - Denmark",
  "Zurich - Switzerland",
  "Geneva - Switzerland",
  "Bern - Switzerland",
  "Athens - Greece",
  "Rhodes - Greece",
  "Corfu - Greece",
  "Crete - Greece",
  "Bruges - Belgium",
  "Brussels - Belgium",
  "Amsterdam - Metherlands",
  "Rotterdam - Netherlands",
  "The Hague - Netherlands",
  "Maastricht - Netherlands",
  "Eindhoven - Netherlands",
  "Istanbul - Turkey",
  "El Paso - Texas",
  "Dallas - Texas",
  "Houston - Texas",
  "Austin - Texas",
  "San Antonio - Texas",
  "Moscow - Russia",
  "Vienna - Austria",
  "Salzburg - Austria",
  "Prague - Czech Republic",
  "Reykjavik - Iceland",
  "Sydney - Australia",
  "Melbourne - Australia",
  "Gold Coast - Australia",
  "Cairns - Australia",
  "Brisbane - Australia",
  "Perth - Australia",
  "Adelaide - Australia",
  "Darwin - Australia",
  "Auckland - New Zealand",
  "Queenstown - New Zealand",
  "Wellington - New Zealand",
  "Christchurch - New Zealand",
  "Kenya - Africa",
  "Egypt - Africa"
]

const place = () => games.map(game => ({
  game,
  hint: 'place'
}))

export default place